require "panos.python"
require "panos.options"
require "panos.spelling"
require "panos.latex"
require "panos.keymaps"
require "panos.plugins"
require "panos.cmp"
require "panos.lsp"
require "panos.treesiter"
require "panos.vimwiki"
require "panos.orgmode_config"
require "panos.abbreviations"
require "panos.gitsigns_config"
require "panos.autopairs"
require "panos.greek"
require "panos.nvim-tree"
require "panos.telescope"
require "panos.toggleterm"
require "panos.dial"
require "panos.commands"
require "panos.lualine"


vim.cmd "colorscheme gruvbox"
